### ISSUE TITLE
Ownership and acknowledgement

### ISSUE THREAD

**Issue by cjordan** [cjordan/hip-sys#1]
Hi @charles-r-earp. As you might see here, I've forked your `hip-sys` repo, and soon I want to release it with some modifications. Given that the original repo is archived, I guess I just formally wanted to check with you that you are happy for me to do so. Maybe I'll supply an acknowledgements section on the readme, that explains that you originally created the code, but now an altered version lives here?  Please let me know what you think. Cheers.

**Comment by charles-r-earp** [comment]
Hello! Yes, I archived it because I wasn't going to continue maintaining it, so you are free to pursue this! :)

**Comment by cjordan** [comment]
Thanks for the fast reply. I'll make some acknowledgement text soon.
